on:
  push:
    branches:
    - main
jobs:
  build:
    name: "test"
    runs-on: alpine:latest
    steps:
      - run: |
          sudo apk update
          sudo apk add zig
          zig build
    
